export default [
    {title:'食品',icon:"icon-shiwu",kind:'food',
    two_lists:[
      {title:'零食',icon:"icon-shiwu",
        three_lists:[
          {title:'饼干'},
          {title:'辣条'},
          {title:'甜品'},
          {title:'果冻'},
        ]
      },
      {title:'饮料',icon:"icon-shiwu",
        three_lists:[
          {title:'可乐'},
          {title:'牛奶'},
          {title:'咖啡'},
          {title:'饮用水'},
        ]
      },
      {title:'肉类',icon:"icon-shiwu",
        three_lists:[
          {title:'鸡肉'},
          {title:'牛肉'},
          {title:'羊肉'},
          {title:'鱼肉'},
        ]
      },
    ],
  },
  {title:'衣服',icon:"icon-clothes",kind:'cloth',
      two_lists:[
      {title:'女装',icon:"icon-shiwu",
        three_lists:[
          {title:'上衣'},
          {title:'下衣'},
          {title:'鞋子'},
          {title:'配饰'},
          {title:'连衣裙'},
        ]
      },
      {title:'男装',icon:"icon-shiwu",
        three_lists:[
          {title:'上衣'},
          {title:'下衣'},
          {title:'鞋子'},
          {title:'配饰'},
        ]
      },
      {title:'童装',icon:"icon-shiwu",
        three_lists:[
          {title:'上衣'},
          {title:'下衣'},
          {title:'鞋子'},
          {title:'配饰'},
        ]
      },
    ],
  },
  {title:'玩具',icon:"icon-wanju",kind:'toy',
    two_lists:[
      {title:'益智玩具',icon:"icon-shiwu",
        three_lists:[
          {title:'积木'},
          {title:'魔方'},
        ]
      },
      {title:'普通玩具',icon:"icon-shiwu",
        three_lists:[
          {title:'毛绒玩具'},
          {title:'卡通模型'},
        ]
      },
    ],
  },
  {title:'电器',icon:"icon-dianqi",kind:'electricalequipment',
      two_lists:[
      {title:'厨房电器',icon:"icon-shiwu",
        three_lists:[
          {title:'抽烟机'},
          {title:'冰箱'},
        ]
      },
      {title:'厕所电器',icon:"icon-shiwu",
        three_lists:[
          {title:'热水器'},
          {title:'洗衣机'},
        ]
      },
      ]
      },
  {title:'学习用品',icon:"icon-xuexiyongpin",kind:'stationery',
      two_lists:[
      {title:'笔',icon:"icon-shiwu",
        three_lists:[
          {title:'钢笔'},
          {title:'自动铅笔'},
          {title:'圆珠笔'},
          {title:'彩笔'},
          {title:'马克笔'},
          {title:'油画笔'},
        ]
      },
      {title:'书',icon:"icon-shiwu",
        three_lists:[
          {title:'科目书'},
          {title:'故事书'},
          {title:'漫画书'},
          {title:'小说'},
        ]
      },
      ]
  },
  {title:'户外用品',icon:"icon-weibiaoti2fuzhi11",kind:'outdoor',
     two_lists:[
      {title:'体育用品',icon:"icon-shiwu",
        three_lists:[
          {title:'球类'},
          {title:'绳类'},
          {title:'极限运动'},
        ]
      },
      {title:'产业用品',icon:"icon-shiwu",
        three_lists:[
          {title:'叉子'},
          {title:'铲子'},
          {title:'斧头'},
        ]
      },
      ]
  },
]